# Generated by Django 3.2.25 on 2024-07-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Автомобиль',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('марка', models.CharField(max_length=100)),
                ('модель', models.CharField(max_length=100)),
                ('год', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Запчасти',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('производитель', models.CharField(max_length=100)),
                ('цена', models.DecimalField(decimal_places=2, max_digits=5)),
                ('автомобиль', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.автомобиль')),
            ],
        ),
        migrations.CreateModel(
            name='Страна',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('код', models.CharField(max_length=3)),
                ('столица', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='parts',
            name='car',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Parts',
        ),
        migrations.AddField(
            model_name='автомобиль',
            name='страна',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.страна'),
        ),
    ]
