# Generated by Django 3.2.25 on 2024-07-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20240704_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='запчасти',
            name='цена',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
