# Generated by Django 5.0.6 on 2024-07-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20240707_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='car',
        ),
        migrations.AddField(
            model_name='parts',
            name='cars',
            field=models.ManyToManyField(related_name='parts', to='data.car', verbose_name='Автомобили'),
        ),
    ]
