# Generated by Django 5.0.6 on 2024-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_parts_car_parts_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='cars',
        ),
        migrations.AddField(
            model_name='car',
            name='parts',
            field=models.ManyToManyField(related_name='cars', to='data.parts', verbose_name='Запчасти'),
        ),
    ]
