# Generated by Django 5.0.6 on 2024-07-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_parts_cars_car_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='kode',
            field=models.IntegerField(),
        ),
    ]
